config/routes.rb
Rails.application.routes.draw do
  resources :drugs
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/drug.rb
class Drug < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/drugs_controller.rb
class DrugsController < ApplicationController
  before_action :set_drug, only: [:show, :edit, :update, :destroy]

  # GET /drugs
  # GET /drugs.json
  def index
    @drugs = Drug.all
  end

  # GET /drugs/1
  # GET /drugs/1.json
  def show
  end

  # GET /drugs/new
  def new
    @drug = Drug.new
  end

  # GET /drugs/1/edit
  def edit
  end

  # POST /drugs
  # POST /drugs.json
  def create
    @drug = Drug.new(drug_params)

    respond_to do |format|
      if @drug.save
        format.html { redirect_to @drug, notice: 'Drug was successfully created.' }
        format.json { render :show, status: :created, location: @drug }
      else
        format.html { render :new }
        format.json { render json: @drug.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /drugs/1
  # PATCH/PUT /drugs/1.json
  def update
    respond_to do |format|
      if @drug.update(drug_params)
        format.html { redirect_to @drug, notice: 'Drug was successfully updated.' }
        format.json { render :show, status: :ok, location: @drug }
      else
        format.html { render :edit }
        format.json { render json: @drug.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /drugs/1
  # DELETE /drugs/1.json
  def destroy
    @drug.destroy
    respond_to do |format|
      format.html { redirect_to drugs_url, notice: 'Drug was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_drug
      @drug = Drug.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def drug_params
      params.require(:drug).permit(:name, :iupac_name, :canonical_smiles, :molecular_formula, :cas_number, :molecular_weight, :klass, :superklass, :rotatable_bond_count, :complexity)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/drugs_helper.rb
module DrugsHelper
end

app/views/drugs/_form.html.erb
<%= form_with(model: drug, local: true) do |form| %>
  <% if drug.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(drug.errors.count, "error") %> prohibited this drug from being saved:</h2>

      <ul>
        <% drug.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :iupac_name, 'IUPAC name' %>
    <%= form.text_field :iupac_name %>
  </div>

  <div class="field">
    <%= form.label :canonical_smiles, 'canonical SMILES' %>
    <%= form.text_field :canonical_smiles %>
  </div>

  <div class="field">
    <%= form.label :molecular_formula %>
    <%= form.text_field :molecular_formula %>
  </div>

  <div class="field">
    <%= form.label :cas_number, 'CAS number' %>
    <%= form.text_field :cas_number %>
  </div>

  <div class="field">
    <%= form.label :molecular_weight %>
    <%= form.text_field :molecular_weight %>
  </div>

  <div class="field">
    <%= form.label :klass, 'Class' %>
    <%= form.text_field :klass %>
  </div>

  <div class="field">
    <%= form.label :superklass, 'Superclass' %>
    <%= form.text_field :superklass %>
  </div>

  <div class="field">
    <%= form.label :rotatable_bond_count %>
    <%= form.text_field :rotatable_bond_count %>
  </div>

  <div class="field">
    <%= form.label :complexity %>
    <%= form.text_field :complexity %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/drugs/edit.html.erb
<h1>Editing Drug</h1>

<%= render 'form', drug: @drug %>

<%= link_to 'Show', @drug %> |
<%= link_to 'Back', drugs_path %>

app/views/drugs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Drugs</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>IUPAC name</th>
      <th>Canonical SMILES</th>
      <th>Molecular formula</th>
      <th>CAS number</th>
      <th>Molecular weight</th>
      <th>Class</th>
      <th>Superclass</th>
      <th>Rotatable bond count</th>
      <th>Complexity</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @drugs.each do |drug| %>
      <tr>
        <td><%= drug.name %></td>
        <td><%= drug.iupac_name %></td>
        <td><%= drug.canonical_smiles %></td>
        <td><%= drug.molecular_formula %></td>
        <td><%= drug.cas_number %></td>
        <td><%= drug.molecular_weight %></td>
        <td><%= drug.klass %></td>
        <td><%= drug.superklass %></td>
        <td><%= drug.rotatable_bond_count %></td>
        <td><%= drug.complexity %></td>
        <td><%= link_to 'Show', drug %></td>
        <td><%= link_to 'Edit', edit_drug_path(drug) %></td>
        <td><%= link_to 'Destroy', drug, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Drug', new_drug_path %>

app/views/drugs/new.html.erb
<h1>New Drug</h1>

<%= render 'form', drug: @drug %>

<%= link_to 'Back', drugs_path %>

app/views/drugs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @drug.name %>
</p>

<p>
  <strong>IUPAC name:</strong>
  <%= @drug.iupac_name %>
</p>

<p>
  <strong>Canonical SMILES:</strong>
  <%= @drug.canonical_smiles %>
</p>

<p>
  <strong>Molecular formula:</strong>
  <%= @drug.molecular_formula %>
</p>

<p>
  <strong>CAS number:</strong>
  <%= @drug.cas_number %>
</p>

<p>
  <strong>Molecular weight:</strong>
  <%= @drug.molecular_weight %>
</p>

<p>
  <strong>Class:</strong>
  <%= @drug.klass %>
</p>

<p>
  <strong>Superclass:</strong>
  <%= @drug.superklass %>
</p>

<p>
  <strong>Rotatable bond count:</strong>
  <%= @drug.rotatable_bond_count %>
</p>

<p>
  <strong>Complexity:</strong>
  <%= @drug.complexity %>
</p>

<%= link_to 'Edit', edit_drug_path(@drug) %> |
<%= link_to 'Back', drugs_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>VerisimLife</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>